site_name: bbstat
site_url: https://cwehmeyer.github.io/bbstat/
repo_url: https://github.com/cwehmeyer/bbstat/
theme:
  name: mkdocs
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - search.highlight
    - search.suggest
    - content.code.copy

plugins:
  - search
  - include-markdown
  - mkdocstrings:
      default_handler: python

nav:
  - Home: index.md
  - API Reference: reference.md
  - Changelog: changelog.md
