[project]
name = "bbstat"
dynamic = ["version"]
authors = [{ name="Chris Wehmeyer", email="wehmeyer.chris@gmail.com" }]
description = "A lightweight library for Bayesian bootstrapping and statistical evaluation."
readme = "README.md"
requires-python = ">=3.10"
license = "MIT"
license-files = ["LICENSE"]
keywords = ["bayesian", "bootstrap", "statistics"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
dependencies = [
    "matplotlib",
    "numpy >= 1.21",
    "scipy >= 1.11",
]

[project.urls]
Homepage = "https://github.com/cwehmeyer/bbstat"
Documentation = "https://cwehmeyer.github.io/bbstat/"
Repository = "https://github.com/cwehmeyer/bbstat.git"
Issues = "https://github.com/cwehmeyer/bbstat/issues"
Changelog = "https://github.com/cwehmeyer/bbstat/blob/main/CHANGELOG.md"

[tool.setuptools]
packages = ["bbstat"]
include-package-data = true

[tool.setuptools_scm]
version_scheme = "guess-next-dev"
local_scheme = "node-and-date"
write_to = "bbstat/_version.py"

[tool.mypy]
check_untyped_defs = true

[tool.mkdocs]
config_file = "mkdocs.yml"

[build-system]
requires = [
    "setuptools >= 77.0.3",
    "setuptools-scm",
    "wheel",
]
build-backend = "setuptools.build_meta"

[project.optional-dependencies]
test = [
    "pytest >= 7.0",
    "pytest-cov",
    "scipy-stubs",
]
docs = [
    "mkdocs",
    "mkdocs-autorefs",
    "mkdocs-get-deps",
    "mkdocs-include-markdown-plugin",
    "mkdocstrings[python]",
]
dev = [
    "black",
    "build",
    "mypy",
    "pre-commit",
    "ruff",
    "tox",
    "twine",
]
